// Side-panel launcher: the toolbar icon opens miniCycle in the browser side panel.
// Generated by web/scripts/build-chrome-full.cjs — do not edit by hand.
//
// miniCycle's full UI is mobile-first, so it fits the side panel's narrow width,
// and the panel gives full browser height (a popup is capped at 600px) while
// persisting alongside the user's work — a checklist they can keep in view while
// doing the tasks. setPanelBehavior({ openPanelOnActionClick: true }) makes the
// action click open the global default panel (manifest "side_panel.default_path").
// The setting persists, so we only need to (re)assert it on install/update.
// An in-app "Open in full tab" button (ext-boot) is the wide-layout escape hatch.
chrome.runtime.onInstalled.addListener(() => {
  chrome.sidePanel.setPanelBehavior({ openPanelOnActionClick: true })
    .catch((e) => console.warn('[miniCycle-ext] setPanelBehavior failed:', e));
});
