// Full-tab launcher: open (or focus) the bundled app in a normal tab.
// Generated by web/scripts/build-chrome-full.cjs — do not edit by hand.
//
// We can't use chrome.tabs.query({ url }) to find our own page: without the
// "tabs" permission the url filter is silently IGNORED and query returns ALL
// tabs — so [first] would be some unrelated tab and the click would hijack it
// instead of opening the app. "tabs" would fix that but adds a "Read your
// browsing history" warning. Instead we remember our launcher tab's id in
// chrome.storage.session ("storage" perm, no warning) and focus it if it's
// still open. tabs.get/update/create and windows.update need no permission.
const APP_URL = chrome.runtime.getURL('index.html');
const TAB_KEY = 'launcherTabId';

async function openOrFocus() {
  const stored = await chrome.storage.session.get(TAB_KEY);
  const tabId = stored[TAB_KEY];
  if (tabId != null) {
    try {
      const tab = await chrome.tabs.get(tabId); // throws if the tab is gone
      await chrome.tabs.update(tab.id, { active: true });
      if (tab.windowId != null) await chrome.windows.update(tab.windowId, { focused: true });
      return;
    } catch (e) {
      // remembered tab was closed — fall through and open a fresh one
    }
  }
  const tab = await chrome.tabs.create({ url: APP_URL });
  await chrome.storage.session.set({ [TAB_KEY]: tab.id });
}

chrome.action.onClicked.addListener(openOrFocus);

// Forget the tab the moment it closes, so the next click opens a fresh one.
chrome.tabs.onRemoved.addListener(async (closedId) => {
  const stored = await chrome.storage.session.get(TAB_KEY);
  if (closedId === stored[TAB_KEY]) await chrome.storage.session.remove(TAB_KEY);
});
