// Full-tab launcher: open (or focus) the bundled app in a normal tab.
// Generated by web/scripts/build-chrome-full.cjs — do not edit by hand.
chrome.action.onClicked.addListener(async () => {
  const url = chrome.runtime.getURL('index.html');
  const [open] = await chrome.tabs.query({ url });
  if (open) {
    chrome.tabs.update(open.id, { active: true });
    if (open.windowId != null) chrome.windows.update(open.windowId, { focused: true });
  } else {
    chrome.tabs.create({ url });
  }
});
