name: Automated Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      working-directory: ./web
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ./web
      run: npx playwright install --with-deps chromium

    - name: Start HTTP server in background
      working-directory: ./web
      run: |
        python3 -m http.server 8080 &
        sleep 3
        echo "Server started on port 8080"

    - name: Run automated browser tests
      working-directory: ./web
      run: npm test
      continue-on-error: false # Set to true if you want workflow to pass even with failing tests

    # Note: Jest tests are currently experimental/incomplete
    # Main test suite (958 browser tests) runs above

    - name: Test summary
      if: always()
      run: echo "✅ Tests completed for Node.js ${{ matrix.node-version }}"
