// Version file - Auto-generated by update-version.sh
// Single source of truth for all version info

// Use globalThis for universal compatibility (window, self, Node, SW)
globalThis.APP_VERSION = '2.538';
globalThis.CACHE_VERSION = 1381;

// Debug markers in modules derive from globalThis.APP_VERSION at runtime
// No separate version constants needed - true single source of truth
